web_search = "live"
model_reasoning_summary = "detailed"
model_verbosity = "medium"


[sandbox_workspace_write]
network_access = true
exclude_tmpdir_env_var = false
exclude_slash_tmp = false

[features]
apps = true
hooks = true
unified_exec = true
shell_snapshot = true
shell_tool = true
multi_agent = true
goals = true
remote_plugin = true
personality = true
fast_mode = true
enable_request_compression = true
skill_mcp_dependency_install = false
prevent_idle_sleep = true
plugin_sharing = true
