import type { StoredPlacementZoneId } from './placement-taxonomy';

export type NameCategoryRule = {
  value: string;
  /** Legacy-Regeln werden im Classifier vor der Auswertung auf V2 normalisiert. */
  categoryId: StoredPlacementZoneId;

  match: 'word' | 'word-start' | 'word-end';
  score: number;
};

/** Explizite, eindeutige Marker (z. B. Tiefkühl-Präfix, Dosen/Konserven) schlagen alles. */
const EXPLICIT_MARKER = 120;
/** Verarbeitete Produkte und Hauptkategorien (Getränke, Süßwaren, Reiniger, Tierfutter, etc.) */
const PRIMARY_PRODUCT = 100;
/** Molkereiprodukte (Butter, Käse, Joghurt, Quark) */
const DAIRY_PRODUCT = 98;
/** Rohes Frischfleisch & Frischfisch */
const RAW_MEAT_FISH = 95;
/** Frisches Obst, Gemüse und Kräuter; in Komposita nachrangig. */
const RAW_PRODUCE = 90;
/** Grundwort-Endungen in Komposita */
const WORD_END = 85;
/** Generische Modifier-Wortanfänge */
const WORD_START = 20;

export const NAME_CATEGORY_RULES: readonly NameCategoryRule[] = [
  // =========================================================================
  // produce (Frisches Obst, Gemüse, Salate, Kräuter)
  // =========================================================================
  ...[
    'apfel',
    'äpfel',
    'banane',
    'bananen',
    'birne',
    'birnen',
    'orange',
    'orangen',
    'mandarine',
    'mandarinen',
    'klementine',
    'klementinen',
    'zitrone',
    'zitronen',
    'limette',
    'limetten',
    'traube',
    'trauben',
    'weintraube',
    'weintrauben',
    'beere',
    'beeren',
    'erdbeere',
    'erdbeeren',
    'himbeere',
    'himbeeren',
    'blaubeere',
    'blaubeeren',
    'heidelbeere',
    'heidelbeeren',
    'brombeere',
    'brombeeren',
    'kirsche',
    'kirschen',
    'pflaume',
    'pflaumen',
    'zwetschge',
    'zwetschgen',
    'pfirsich',
    'pfirsiche',
    'nektarine',
    'nektarinen',
    'aprikose',
    'aprikosen',
    'kiwi',
    'kiwis',
    'ananas',
    'mango',
    'mangos',
    'avocado',
    'avocados',
    'melone',
    'melonen',
    'wassermelone',
    'wassermelonen',
    'honigmelone',
    'honigmelonen',
    'tomate',
    'tomaten',
    'rispentomaten',
    'strauchtomaten',
    'fleischtomaten',
    'cherrytomaten',
    'gurke',
    'gurken',
    'salatgurke',
    'salatgurken',
    'minigurke',
    'salat',
    'salate',
    'kopfsalat',
    'eisbergsalat',
    'feldsalat',
    'rucola',
    'romana',
    'endivie',
    'chicoree',
    'paprika',
    'paprikas',
    'spitzpaprika',
    'zucchini',
    'zucchinis',
    'aubergine',
    'auberginen',
    'karotte',
    'karotten',
    'möhre',
    'möhren',
    'kartoffel',
    'kartoffeln',
    'süßkartoffel',
    'süßkartoffeln',
    'zwiebel',
    'zwiebeln',
    'speisezwiebeln',
    'gemüsezwiebeln',
    'rote zwiebeln',
    'schalotte',
    'schalotten',
    'knoblauch',
    'knoblauchzehe',
    'lauch',
    'porree',
    'frühlingszwiebel',
    'frühlingszwiebeln',
    'lauchzwiebel',
    'lauchzwiebeln',
    'brokkoli',
    'blumenkohl',
    'spinat',
    'blattspinat',
    'pilz',
    'pilze',
    'champignon',
    'champignons',
    'steinpilz',
    'pfifferling',
    'pfifferlinge',
    'austernpilze',
    'kräuterseitlinge',
    'sellerie',
    'knollensellerie',
    'stangensellerie',
    'radieschen',
    'rettich',
    'kohl',
    'rotkohl',
    'weißkohl',
    'wirsing',
    'spitzkohl',
    'rosenkohl',
    'grünkohl',
    'kohlrabi',
    'kürbis',
    'hokkaido',
    'butternut',
    'ingwer',
    'kurkumawurzel',
    'spargel',
    'obst',
    'gemüse',
    'kräuter',
    'basilikum',
    'petersilie',
    'rosmarin',
    'thymian',
    'dill',
    'schnittlauch',
    'koriander',
    'minze',
    'salbei',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'produce',
      match: 'word',
      score: RAW_PRODUCE,
    }),
  ),
  { value: 'apfel', categoryId: 'produce', match: 'word-start', score: WORD_START },
  { value: 'salat', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'tomate', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'tomaten', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'gurke', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'gurken', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'kohl', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'zwiebel', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'zwiebeln', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'kartoffel', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'kartoffeln', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'pilz', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'pilze', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'beere', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'beeren', categoryId: 'produce', match: 'word-end', score: WORD_END },
  { value: 'spinat', categoryId: 'produce', match: 'word-end', score: WORD_END },

  // =========================================================================
  // bakery (Brot & Backwaren)
  // =========================================================================
  ...[
    'brot',
    'brote',
    'brötchen',
    'semmel',
    'semmeln',
    'kaisersemmel',
    'kaisersemmeln',
    'baguette',
    'baguettes',
    'croissant',
    'croissants',
    'toast',
    'toastbrot',
    'vollkornbrot',
    'roggenbrot',
    'mischbrot',
    'dinkelbrot',
    'weißbrot',
    'graubrot',
    'sonnenblumenbrot',
    'brezel',
    'brezeln',
    'laugenbrezel',
    'laugenbrezeln',
    'laugenstange',
    'laugenstangen',
    'laugenbrötchen',
    'kuchen',
    'marmorkuchen',
    'streuselkuchen',
    'hefezopf',
    'muffin',
    'muffins',
    'torte',
    'torten',
    'gebäck',
    'feingebäck',
    'waffel',
    'waffeln',
    'eierwaffeln',
    'bagel',
    'bagels',
    'fladenbrot',
    'pita',
    'ciabatta',
    'panini',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'bakery',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'brot', categoryId: 'bakery', match: 'word-end', score: WORD_END },
  { value: 'brötchen', categoryId: 'bakery', match: 'word-end', score: WORD_END },
  { value: 'kuchen', categoryId: 'bakery', match: 'word-end', score: WORD_END },
  { value: 'semmel', categoryId: 'bakery', match: 'word-end', score: WORD_END },
  { value: 'semmeln', categoryId: 'bakery', match: 'word-end', score: WORD_END },
  { value: 'waffeln', categoryId: 'bakery', match: 'word-end', score: WORD_END },

  // =========================================================================
  // convenience (Snacks to go, Sushi, frische Sandwiches)
  // =========================================================================
  ...[
    'fertigsalat',
    'sandwich',
    'sandwiches',
    'wraps',
    'wrap',
    'sushi',
    'feinkost',
    'tortellini',
    'gnocchi',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'convenience',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),

  // =========================================================================
  // breakfast (Müsli, Honig, Marmelade, Aufstriche)
  // =========================================================================
  ...[
    'müsli',
    'früchtemüsli',
    'knuspermüsli',
    'schokomüsli',
    'haferflocken',
    'cornflakes',
    'granola',
    'crunchy',
    'porridge',
    'cerealien',
    'marmelade',
    'erdbeermarmelade',
    'himbeermarmelade',
    'konfitüre',
    'gelee',
    'pflaumenmus',
    'honig',
    'blütenhonig',
    'waldhonig',
    'akazienhonig',
    'nutella',
    'schokocreme',
    'haselnusscreme',
    'nuss-nougat-creme',
    'erdnussbutter',
    'mandelmus',
    'erdnussmus',
    'agavendicksaft',
    'ahornsirup',
    'zuckerrübensirup',
    'rübenkraut',
    'aufstrich',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'breakfast',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'müsli', categoryId: 'breakfast', match: 'word-end', score: WORD_END },
  { value: 'honig', categoryId: 'breakfast', match: 'word-end', score: WORD_END },
  { value: 'marmelade', categoryId: 'breakfast', match: 'word-end', score: WORD_END },
  { value: 'konfitüre', categoryId: 'breakfast', match: 'word-end', score: WORD_END },

  // =========================================================================
  // hot_beverages (Kaffee, Tee, Kakao)
  // =========================================================================
  ...[
    'kaffee',
    'kaffeebohnen',
    'filterkaffee',
    'espresso',
    'espressobohnen',
    'cappuccino',
    'kaffepads',
    'kaffeepads',
    'kaffeekapseln',
    'tee',
    'schwarztee',
    'grüntee',
    'kräutertee',
    'früchtetee',
    'kamillentee',
    'pfefferminztee',
    'rooibos',
    'fencheltee',
    'chai',
    'matcha',
    'trinkkakao',
    'kakaogetränk',
    'trinkschokolade',
    'filtertüten',
    'kaffefilter',
    'kaffeefilter',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'hot_beverages',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'kakao', categoryId: 'hot_beverages', match: 'word', score: RAW_MEAT_FISH },
  { value: 'tee', categoryId: 'hot_beverages', match: 'word-end', score: WORD_END },
  { value: 'kaffee', categoryId: 'hot_beverages', match: 'word-end', score: WORD_END },
  { value: 'filter', categoryId: 'hot_beverages', match: 'word-end', score: WORD_END },

  // =========================================================================
  // pantry_staples (Nudeln, Reis, Mehl, Zucker, Hülsenfrüchte)
  // =========================================================================
  ...[
    'nudeln',
    'pasta',
    'spaghetti',
    'penne',
    'fusilli',
    'farfalle',
    'rigatoni',
    'tagliatelle',
    'bandnudeln',
    'lasagneplatten',
    'macaroni',
    'makkaroni',
    'spätzle',
    'reis',
    'basmati',
    'basmatireis',
    'jasminreis',
    'milchreis',
    'risottoreis',
    'langkornreis',
    'wildreis',
    'parboiled',
    'mehl',
    'weizenmehl',
    'dinkelmehl',
    'roggenmehl',
    'vollkornmehl',
    'zucker',
    'rohrzucker',
    'puderzucker',
    'hagelzucker',
    'linsen',
    'tellerlinsen',
    'berglinsen',
    'kichererbsen',
    'kidneybohnen',
    'weiße bohnen',
    'couscous',
    'bulgur',
    'quinoa',
    'polenta',
    'hafer',
    'grieß',
    'hartweizengrieß',
    'weichweizengrieß',
    'graupen',
    'hirse',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'pantry_staples',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'nudeln', categoryId: 'pantry_staples', match: 'word-end', score: WORD_END },
  { value: 'pasta', categoryId: 'pantry_staples', match: 'word-end', score: WORD_END },
  { value: 'reis', categoryId: 'pantry_staples', match: 'word-end', score: WORD_END },
  { value: 'mehl', categoryId: 'pantry_staples', match: 'word-end', score: WORD_END },
  { value: 'grieß', categoryId: 'pantry_staples', match: 'word-end', score: WORD_END },
  { value: 'linsen', categoryId: 'pantry_staples', match: 'word-end', score: WORD_END },

  // =========================================================================
  // cooking_baking (Öle, Essig, Gewürze, Salz, Backzutaten)
  // =========================================================================
  ...[
    'öl',
    'olivenöl',
    'rapsöl',
    'sonnenblumenöl',
    'speiseöl',
    'leinöl',
    'sesamöl',
    'kokosöl',
    'bratöl',
    'essig',
    'balsamico',
    'apfelessig',
    'weinessig',
    'branntweinessig',
    'salz',
    'speisesalz',
    'jodsalz',
    'meersalz',
    'steinsalz',
    'pfeffer',
    'schwarzer pfeffer',
    'weißer pfeffer',
    'gewürz',
    'gewürze',
    'paprikapulver',
    'curry',
    'currypulver',
    'oregano',
    'zimt',
    'kurkuma',
    'muskat',
    'muskatnuss',
    'kümmel',
    'kreuzkümmel',
    'chili',
    'chiliflocken',
    'lorbeer',
    'lorbeerblätter',
    'knoblauchpulver',
    'topping',
    'toppings',
    'gewürzmischung',
    'gewürzzubereitung',
    'kräutermischung',
    'backkakao',
    'kakaopulver',
    'rohkakao',
    'kakaobutter',
    'backtrennspray',
    'würzmix',
    'gewürzmix',
    'backpulver',
    'vanillezucker',
    'vanilleextrakt',
    'hefe',
    'frischhefe',
    'trockenhefe',
    'natron',
    'speisestärke',
    'speisestaerke',
    'kuvertüre',
    'zuckerstreusel',
    'backaroma',
    'gelatine',
    'agar agar',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'cooking_baking',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'öl', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'essig', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'salz', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'pfeffer', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'pulver', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'hefe', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'topping', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'mischung', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },
  { value: 'würzmix', categoryId: 'cooking_baking', match: 'word-end', score: WORD_END },

  // =========================================================================
  // canned_sauces (Konserven, Saucen, Fertiggerichte, Dosen)
  // =========================================================================
  ...[
    'pesto',
    'ketchup',
    'curryketchup',
    'mayonnaise',
    'mayo',
    'senf',
    'dijonsenf',
    'remoulade',
    'sauce',
    'saucen',
    'soße',
    'soßen',
    'pastasauce',
    'tomatensauce',
    'bolognese',
    'arrabbiata',
    'suppe',
    'suppen',
    'tomatensuppe',
    'hühnersuppe',
    'gulaschsuppe',
    'brühe',
    'gemüsebrühe',
    'hühnerbrühe',
    'rinderbrühe',
    'fertiggericht',
    'fertiggerichte',
    'ravioli',
    'lasagne',
    'eintopf',
    'linseneintopf',
    'erbseneintopf',
    'tomatenmark',
    'passata',
    'pizzatomaten',
    'schältomaten',
    'gehackte tomaten',
    'kokosmilch',
    'sauerkraut',
    'rotkohl',
    'gewürzgurke',
    'gewürzgurken',
    'sauergurke',
    'sauergurken',
    'essiggurke',
    'essiggurken',
    'cornichons',
    'apfelmus',
    'apfelmark',
    'fruchtmark',
    'kompott',
    'mus',
    'schattenmorellen',
    'artischocken',
    'oliven',
    'kapern',
    'thunfisch',
    'thunfischdose',
    'sardinen',
    'dressing',
    'salatdressing',
    'tabasco',
    'bbq-sauce',
    'sojasauce',
    'teriyaki',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'canned_sauces',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  ...[
    'dose',
    'dosen',
    'konserve',
    'konserven',
    'eingelegt',
    'eingelegte',
    'eingelegter',
    'eingelegtes',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'canned_sauces',
      match: 'word',
      score: EXPLICIT_MARKER,
    }),
  ),
  { value: 'dosen', categoryId: 'canned_sauces', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'eingelegt', categoryId: 'canned_sauces', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'konserve', categoryId: 'canned_sauces', match: 'word-end', score: EXPLICIT_MARKER },
  { value: 'ketchup', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },
  { value: 'suppe', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },
  { value: 'brühe', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },
  { value: 'eintopf', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },
  { value: 'mark', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },
  { value: 'mus', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },
  { value: 'kompott', categoryId: 'canned_sauces', match: 'word-end', score: WORD_END },

  // =========================================================================
  // snacks (Süßwaren & herzhafte Snacks)
  // =========================================================================
  ...[
    'schokolade',
    'vollmilchschokolade',
    'zartbitterschokolade',
    'weiße schokolade',
    'pralinen',
    'chips',
    'kartoffelchips',
    'stapelchips',
    'tortilla chips',
    'nachos',
    'erdnussflips',
    'flips',
    'salzstangen',
    'salzbrezeln',
    'gummibärchen',
    'fruchtgummi',
    'lakritz',
    'bonbon',
    'bonbons',
    'fruchtbonbons',
    'hustenbonbons',
    'kekse',
    'butterkekse',
    'cookies',
    'keks',
    'neapolitaner',
    'nüsse',
    'erdnüsse',
    'cashews',
    'cashewkerne',
    'mandeln',
    'walnüsse',
    'haselnüsse',
    'pistazien',
    'studentenfutter',
    'nussmischung',
    'cracker',
    'popcorn',
    'riegel',
    'müsliriegel',
    'schokoriegel',
    'schnitten',
    'waffelschnitten',
    'süßigkeiten',
    'snack',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'snacks',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'schokolade', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'chips', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'flips', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'kekse', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'schnitten', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'nüsse', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'kerne', categoryId: 'snacks', match: 'word-end', score: WORD_END },
  { value: 'bonbons', categoryId: 'snacks', match: 'word-end', score: WORD_END },

  // =========================================================================
  // beverages (Getränke & Alkohol)
  // =========================================================================
  ...[
    'wasser',
    'mineralwasser',
    'sprudel',
    'sprudelwasser',
    'stilles wasser',
    'saft',
    'orangensaft',
    'multivitaminsaft',
    'direktsaft',
    'traubensaft',
    'kirschsaft',
    'cola',
    'cola zero',
    'limonade',
    'zitronenlimonade',
    'orangenlimonade',
    'fanta',
    'sprite',
    'spezi',
    'eistee',
    'tea',
    'icetea',
    'ice-tea',
    'schorle',
    'apfelschorle',
    'sprizz',
    'spritz',
    'mate',
    'bionade',
    'brause',
    'fassbrause',
    'nektar',
    'fruchtsaft',
    'fruchtschorle',
    'energy drink',
    'energydrink',
    'energy',
    'tonic water',
    'tonic',
    'bitter lemon',
    'ginger ale',
    'softdrink',
    'smoothie',
    'shot',
    'ingwershot',
    'sirup',
    'getränkesirup',
    'bier',
    'pils',
    'pilsener',
    'weizenbier',
    'hefeweizen',
    'radler',
    'alkoholfreies bier',
    'wein',
    'rotwein',
    'weißwein',
    'weisswein',
    'roséwein',
    'rosewein',
    'sekt',
    'prosecco',
    'champagner',
    'cava',
    'cider',
    'gin',
    'vodka',
    'rum',
    'whisky',
    'whiskey',
    'aperol',
    'likör',
    'schnaps',
    'korn',
    'ouzo',
    'tequila',
    'brandy',
    'cognac',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'beverages',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'saft', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'wasser', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'limonade', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'schorle', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'sprizz', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'spritz', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'nektar', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'brause', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'shot', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'bier', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'wein', categoryId: 'beverages', match: 'word-end', score: WORD_END },
  { value: 'sekt', categoryId: 'beverages', match: 'word-end', score: WORD_END },

  // =========================================================================
  // drugstore (Körperpflege, Drogerie, Hygiene)
  // =========================================================================
  ...[
    'shampoo',
    'antischuppenshampoo',
    'duschgel',
    'cremedusche',
    'haarspülung',
    'haarkur',
    'haarspray',
    'haargel',
    'seife',
    'flüssigseife',
    'arztseife',
    'zahnpasta',
    'zahncreme',
    'zahnbürste',
    'zahnbürsten',
    'mundspülung',
    'zahnseide',
    'deo',
    'deodorant',
    'deospray',
    'deoroller',
    'bodylotion',
    'gesichtscreme',
    'tagescreme',
    'nachtcreme',
    'handcreme',
    'körperlotion',
    'rasierer',
    'einwegrasierer',
    'rasierklingen',
    'rasierschaum',
    'rasiergel',
    'aftershave',
    'wattepads',
    'wattestäbchen',
    'tampons',
    'damenbinden',
    'binden',
    'slipeinlagen',
    'pflaster',
    'sonnencreme',
    'sonnenmilch',
    'aftersun',
    'duschschaum',
    'badeschaum',
    'lippenbalsam',
    'labello',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'drugstore',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'creme', categoryId: 'drugstore', match: 'word', score: WORD_END },
  { value: 'shampoo', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'seife', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'creme', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'lotion', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'schaum', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'spray', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'roller', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'pasta', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'bürste', categoryId: 'drugstore', match: 'word-end', score: WORD_END },
  { value: 'binden', categoryId: 'drugstore', match: 'word-end', score: WORD_END },

  // =========================================================================
  // baby_kids (Babybedarf & Babynahrung)
  // =========================================================================
  ...[
    'windeln',
    'pampers',
    'babypants',
    'feuchttücher',
    'babyfeuchttücher',
    'babynahrung',
    'gläschen',
    'babygläschen',
    'folgemilch',
    'pre-milch',
    'premilch',
    'babybrei',
    'grießbrei',
    'milchbrei',
    'babyöl',
    'babycreme',
    'wundschutzcreme',
    'babyshampoo',
    'babypuder',
    'schnuller',
    'trinklernbecher',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'baby_kids',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'windeln', categoryId: 'baby_kids', match: 'word-end', score: WORD_END },

  // =========================================================================
  // household (Haushalt & Reinigung)
  // =========================================================================
  ...[
    'toilettenpapier',
    'klopapier',
    'küchenrolle',
    'küchentücher',
    'taschentücher',
    'kosmetiktücher',
    'spülmittel',
    'geschirrspülmittel',
    'spülmaschinentabs',
    'geschirrspültabs',
    'klarspüler',
    'spülsalz',
    'waschmittel',
    'vollwaschmittel',
    'colorwaschmittel',
    'feinwaschmittel',
    'weichspüler',
    'fleckenentferner',
    'putzmittel',
    'reiniger',
    'wc',
    'allzweckreiniger',
    'glasreiniger',
    'badreiniger',
    'wc-reiniger',
    'kalkreiniger',
    'scheuermilch',
    'insektenspray',
    'enteiserspray',
    'mückenspray',
    'müllbeutel',
    'mülltüten',
    'müllsäcke',
    'alufolie',
    'backpapier',
    'frischhaltefolie',
    'schwamm',
    'topfschwamm',
    'spültuch',
    'mikrofasertuch',
    'putzlappen',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'household',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'reiniger', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'waschmittel', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'spülmittel', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'papier', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'beutel', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'tabs', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'folie', categoryId: 'household', match: 'word-end', score: WORD_END },
  { value: 'schwamm', categoryId: 'household', match: 'word-end', score: WORD_END },

  // =========================================================================
  // pet_supplies (Tiernahrung & Tierbedarf)
  // =========================================================================
  ...[
    'katzenfutter',
    'hundefutter',
    'katzenstreu',
    'vogelfutter',
    'nassfutter',
    'trockenfutter',
    'hundeleckerli',
    'katzenleckerli',
    'hundesnacks',
    'katzensnacks',
    'knuspertaschen',
    'kauknochen',
    'tiernahrung',
    'katzengras',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'pet_supplies',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'futter', categoryId: 'pet_supplies', match: 'word-end', score: WORD_END },
  { value: 'streu', categoryId: 'pet_supplies', match: 'word-end', score: WORD_END },
  { value: 'leckerli', categoryId: 'pet_supplies', match: 'word-end', score: WORD_END },

  // =========================================================================
  // meat_poultry (Frischfleisch & Geflügel)
  // =========================================================================
  ...[
    'hackfleisch',
    'rinderhackfleisch',
    'rinderhack',
    'gemischtes hack',
    'schweinehackfleisch',
    'hähnchen',
    'hähnchenbrust',
    'hähnchenfilet',
    'hähnchenschenkel',
    'hähnchenkeule',
    'hühnchen',
    'hühnerbrust',
    'huhn',
    'suppenhuhn',
    'pute',
    'putenbrust',
    'putenbrustfilet',
    'putenschnitzel',
    'putengeschnetzeltes',
    'rindfleisch',
    'rinderbraten',
    'rindergulasch',
    'rindersteak',
    'schweinefleisch',
    'schweinebraten',
    'schweinefilet',
    'schweineschnitzel',
    'schweinekotelett',
    'schnitzel',
    'steak',
    'rumpsteak',
    'ribeye',
    'entrecote',
    'filetsteak',
    'gulasch',
    'kotelett',
    'ente',
    'entenbrust',
    'gans',
    'gänsekeule',
    'lamm',
    'lammfleisch',
    'lammkotelett',
    'lammlachs',
    'kalbfleisch',
    'kalbsschnitzel',
    'fleisch',
    'schwein',
    'rind',
    'bratwurst',
    'roastbeef',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'meat_poultry',
      match: 'word',
      score: RAW_MEAT_FISH,
    }),
  ),
  { value: 'hähnchen', categoryId: 'meat_poultry', match: 'word-start', score: WORD_START },
  { value: 'schwein', categoryId: 'meat_poultry', match: 'word-start', score: WORD_START },
  { value: 'rind', categoryId: 'meat_poultry', match: 'word-start', score: WORD_START },
  { value: 'fleisch', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'hackfleisch', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'schnitzel', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'steak', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'gulasch', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'kotelett', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'brust', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'braten', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },
  { value: 'keule', categoryId: 'meat_poultry', match: 'word-end', score: WORD_END },

  // =========================================================================
  // fish_seafood (Fisch & Meeresfrüchte frisch/gekühlt)
  // =========================================================================
  ...[
    'lachs',
    'lachsfilet',
    'forelle',
    'lachsforelle',
    'garnelen',
    'riesengarnelen',
    'king prawns',
    'shrimps',
    'crevetten',
    'krabben',
    'nordseekrabben',
    'thunfisch',
    'thunfischsteak',
    'kabeljau',
    'kabeljaufilet',
    'dorade',
    'wolfsbarsch',
    'scholle',
    'schollenfilet',
    'seelachs',
    'rotbarsch',
    'zander',
    'fisch',
    'meeresfrüchte',
    'muscheln',
    'miesmuscheln',
    'jakobsmuscheln',
    'tintenfisch',
    'calamari',
    'oktopus',
    'matjes',
    'matjesfilet',
    'hering',
    'räucherlachs',
    'stremellachs',
    'makrele',
    'makrelen',
    'makrelenfilet',
    'makrelenfilets',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'fish_seafood',
      match: 'word',
      score: RAW_MEAT_FISH,
    }),
  ),
  { value: 'fisch', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },
  { value: 'lachs', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },
  { value: 'forelle', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },
  { value: 'garnelen', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },
  { value: 'muscheln', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },
  { value: 'makrele', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },
  { value: 'makrelen', categoryId: 'fish_seafood', match: 'word-end', score: WORD_END },

  // =========================================================================
  // deli_cold_cuts (Wurst, Schinken, Feinkost, Dips)
  // =========================================================================
  ...[
    'wurst',
    'schinken',
    'kochschinken',
    'rohschinken',
    'schwarzwälder schinken',
    'parmaschinken',
    'serrano',
    'salami',
    'edelsalami',
    'paprikasalami',
    'speck',
    'bratenspeck',
    'durchwachsener speck',
    'bacon',
    'leberkäse',
    'fleischkäse',
    'mett',
    'thüringer mett',
    'wiener',
    'wiener würstchen',
    'bockwurst',
    'frankfurter',
    'lyoner',
    'mortadella',
    'fleischwurst',
    'gyros',
    'aufschnitt',
    'wurstaufschnitt',
    'leberwurst',
    'kalbsleberwurst',
    'teewurst',
    'chorizo',
    'prosciutto',
    'hummus',
    'guacamole',
    'tzatziki',
    'zaziki',
    'krautsalat',
    'kartoffelsalat',
    'nudelsalat',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'deli_cold_cuts',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'wurst', categoryId: 'deli_cold_cuts', match: 'word-end', score: WORD_END },
  { value: 'schinken', categoryId: 'deli_cold_cuts', match: 'word-end', score: WORD_END },
  { value: 'salami', categoryId: 'deli_cold_cuts', match: 'word-end', score: WORD_END },
  { value: 'speck', categoryId: 'deli_cold_cuts', match: 'word-end', score: WORD_END },
  { value: 'würstchen', categoryId: 'deli_cold_cuts', match: 'word-end', score: WORD_END },

  // =========================================================================
  // plant_based (Vegane Alternativen & Tofu)
  // =========================================================================
  ...[
    'tofu',
    'räuchertofu',
    'seidentofu',
    'tempeh',
    'seitan',
    'hafermilch',
    'sojamilch',
    'mandelmilch',
    'haferdrink',
    'sojadrink',
    'mandeldrink',
    'kokosdrink',
    'reismilch',
    'sojajoghurt',
    'kokosjoghurt',
    'haferjoghurt',
    'veggie',
    'veganes hack',
    'fleischersatz',
    'soja-geschnetzeltes',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'plant_based',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'tofu', categoryId: 'plant_based', match: 'word-end', score: WORD_END },
  { value: 'drink', categoryId: 'plant_based', match: 'word-end', score: WORD_END },

  // =========================================================================
  // dairy_eggs (Frische Molkerei & Eier)
  // =========================================================================
  ...[
    'milch',
    'frischmilch',
    'fettarme milch',
    'weidemilch',
    'heumilch',
    'rohmilch',
    'butter',
    'markenbutter',
    'deutsche markenbutter',
    'süßrahmbutter',
    'sauerrahmbutter',
    'kräuterbutter',
    'margarine',
    'joghurt',
    'fruchtjoghurt',
    'naturjoghurt',
    'griechischer joghurt',
    'skyr',
    'käse',
    'gouda',
    'junger gouda',
    'mittelalter gouda',
    'butterkäse',
    'tilsiter',
    'emmentaler',
    'cheddar',
    'mozzarella',
    'büffelmozzarella',
    'parmesan',
    'grana padano',
    'pecorino',
    'feta',
    'schafskäse',
    'ziegenkäse',
    'frischkäse',
    'körniger frischkäse',
    'hüttenkäse',
    'camembert',
    'brie',
    'halloumi',
    'ricotta',
    'mascarpone',
    'sahne',
    'schlagsahne',
    'saure sahne',
    'sauerrahm',
    'schmand',
    'crème fraîche',
    'creme fraiche',
    'crème',
    'fraîche',
    'fraiche',
    'quark',
    'speisequark',
    'magerquark',
    'kefir',
    'buttermilch',
    'ei',
    'eier',
    'freilandeier',
    'bio-eier',
    'bodenhaltung',
    'hühnereier',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'dairy_eggs',
      match: 'word',
      score: DAIRY_PRODUCT,
    }),
  ),
  { value: 'milch', categoryId: 'dairy_eggs', match: 'word-end', score: WORD_END },
  { value: 'butter', categoryId: 'dairy_eggs', match: 'word-end', score: WORD_END },
  { value: 'käse', categoryId: 'dairy_eggs', match: 'word-end', score: WORD_END },
  { value: 'quark', categoryId: 'dairy_eggs', match: 'word-end', score: WORD_END },
  { value: 'sahne', categoryId: 'dairy_eggs', match: 'word-end', score: WORD_END },
  { value: 'joghurt', categoryId: 'dairy_eggs', match: 'word-end', score: WORD_END },

  // =========================================================================
  // frozen (Tiefkühl)
  // =========================================================================
  ...[
    'eiscreme',
    'eis',
    'speiseeis',
    'wassereis',
    'vanilleeis',
    'schokoeis',
    'fischstäbchen',
    'pommes',
    'pommes frites',
    'kroketten',
    'kartoffelecken',
    'rösti',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'frozen',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  ...[
    'tiefgekühlt',
    'tiefgekühlte',
    'tiefgekühlter',
    'tiefgekühltes',
    'tiefgefroren',
    'tiefgefrorene',
    'tiefgefrorener',
    'tiefgefrorenes',
    'tiefkühl',
    'tiefgefrier',
    'gefroren',
    'gefrorene',
    'gefrorener',
    'gefrorenes',
    'tk',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'frozen',
      match: 'word',
      score: EXPLICIT_MARKER,
    }),
  ),
  { value: 'tiefkühl', categoryId: 'frozen', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'tiefgefrier', categoryId: 'frozen', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'tiefgefroren', categoryId: 'frozen', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'gefroren', categoryId: 'frozen', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'tk-', categoryId: 'frozen', match: 'word-start', score: EXPLICIT_MARKER },
  { value: 'eis', categoryId: 'frozen', match: 'word-end', score: WORD_END },
  { value: 'stäbchen', categoryId: 'frozen', match: 'word-end', score: WORD_END },

  // =========================================================================
  // checkout (Kassenzone & Non-Food)
  // =========================================================================
  ...[
    'kaugummi',
    'airwaves',
    'wrigleys',
    'kaugummi-dragees',
    'mentos',
    'batterie',
    'batterien',
    'mignon-batterie',
    'micro-batterie',
    'knopfbatterie',
    'zeitschrift',
    'magazin',
    'spiegel',
    'zeitung',
    'feuerzeug',
    'einwegfeuerzeug',
    'feuerzeuge',
    'streichhölzer',
    'gutscheinkarte',
    'gutschein',
    'geschenkkarte',
  ].map(
    (value): NameCategoryRule => ({
      value,
      categoryId: 'checkout',
      match: 'word',
      score: PRIMARY_PRODUCT,
    }),
  ),
  { value: 'kaugummi', categoryId: 'checkout', match: 'word-end', score: WORD_END },
  { value: 'batterie', categoryId: 'checkout', match: 'word-end', score: WORD_END },
  { value: 'batterien', categoryId: 'checkout', match: 'word-end', score: WORD_END },
  { value: 'feuerzeug', categoryId: 'checkout', match: 'word-end', score: WORD_END },
  { value: 'gutschein', categoryId: 'checkout', match: 'word-end', score: WORD_END },
];
