import type { StoredPlacementZoneId } from './placement-taxonomy';

export type OffCategoryRule = {
  /** Kanonischer Open-Food-Facts-Tag, z. B. `en:porks`. Keine Anzeigenamen. */
  tag: string;
  /** Legacy-Regeln werden im Classifier vor der Auswertung auf V2 normalisiert. */
  categoryId: StoredPlacementZoneId;
  /** Höher gewinnt. Spezifische Tags stehen über Oberkategorien. */
  priority: number;
};

/**
 * Priorität-Tiers: spezifische Tags (z. B. `en:porks`) stehen bewusst über
 * Oberkategorien (z. B. `en:meats`) über generischen Sammel-Tags
 * (z. B. `en:beverages`) — siehe `docs/issue#223_V2.md` Abschnitt 7.
 */
const SPECIFIC = 100;
const MID = 50;
const GENERIC = 10;

export const OFF_CATEGORY_RULES: readonly OffCategoryRule[] = [
  // produce
  { tag: 'en:fresh-vegetables', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:fresh-fruits', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:fresh-herbs', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:fresh-salads', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:fresh-mushrooms', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:raw-fruits', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:raw-vegetables', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:apples', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:bananas', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:berries', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:citrus', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:potatoes', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:onions', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:garlic', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:tomatoes', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:cucumbers', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:carrots', categoryId: 'produce', priority: SPECIFIC },
  { tag: 'en:salads', categoryId: 'produce', priority: MID },
  { tag: 'en:fruits', categoryId: 'produce', priority: MID },
  { tag: 'en:vegetables', categoryId: 'produce', priority: MID },

  // bakery
  { tag: 'en:breads', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:viennoiseries', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:baguettes', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:buns', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:sliced-breads', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:rusks', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:toast', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:croissants', categoryId: 'bakery', priority: SPECIFIC },
  { tag: 'en:cakes', categoryId: 'bakery', priority: MID },
  { tag: 'en:pastries', categoryId: 'bakery', priority: MID },
  { tag: 'en:pies', categoryId: 'bakery', priority: MID },
  { tag: 'en:tarts', categoryId: 'bakery', priority: MID },

  // convenience / ready_meals
  { tag: 'en:sandwiches', categoryId: 'convenience', priority: SPECIFIC },
  { tag: 'en:prepared-salads', categoryId: 'convenience', priority: SPECIFIC },
  { tag: 'en:sushi', categoryId: 'convenience', priority: SPECIFIC },
  { tag: 'en:meals', categoryId: 'convenience', priority: SPECIFIC },
  { tag: 'en:ready-meals', categoryId: 'convenience', priority: SPECIFIC },
  { tag: 'en:instant-noodles', categoryId: 'convenience', priority: SPECIFIC },

  // breakfast
  { tag: 'en:breakfast-cereals', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:mueslis', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:flakes', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:rolled-oats', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:granola', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:jams', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:marmalades', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:honeys', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:nut-butters', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:peanut-butters', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:chocolate-spreads', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:sweet-spreads', categoryId: 'breakfast', priority: SPECIFIC },
  { tag: 'en:spreads', categoryId: 'breakfast', priority: MID },
  { tag: 'en:breakfasts', categoryId: 'breakfast', priority: MID },

  // hot_beverages
  { tag: 'en:coffees', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:ground-coffees', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:coffee-beans', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:instant-coffees', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:coffee-capsules', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:teas', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:black-teas', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:green-teas', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:herbal-teas', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:fruit-teas', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:cocoas-and-chocolates-powders', categoryId: 'hot_beverages', priority: SPECIFIC },
  { tag: 'en:hot-beverages', categoryId: 'hot_beverages', priority: MID },

  // pantry_staples / pasta / rice
  { tag: 'en:pastas', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:dry-pastas', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:fresh-pastas', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:egg-pastas', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:spaghetti', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:noodles', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:rices', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:basmati-rices', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:jasmine-rices', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:grains', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:couscous', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:quinoa', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:bulgur', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:lentils', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:dried-beans', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:chickpeas', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:flours', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:wheat-flours', categoryId: 'pantry_staples', priority: SPECIFIC },
  { tag: 'en:legumes', categoryId: 'pantry_staples', priority: MID },

  // cooking_baking
  { tag: 'en:vegetable-oils', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:olive-oils', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:sunflower-oils', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:rapeseed-oils', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:vinegars', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:balsamic-vinegars', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:spices', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:peppers', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:salts', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:baking-powders', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:yeasts', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:starches', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:sugars', categoryId: 'cooking_baking', priority: SPECIFIC },
  { tag: 'en:sweeteners', categoryId: 'cooking_baking', priority: SPECIFIC },

  // canned_sauces
  { tag: 'en:canned-vegetables', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:canned-fruits', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:compotes', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:apple-compotes', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:applesauces', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:fruit-compotes', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:pickled-vegetables', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:pickles', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:pickled-cucumbers', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:olives', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:tomato-sauces', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:passata', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:tomato-pastes', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:pesto', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:pasta-sauces', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:soups', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:canned-soups', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:canned-fishes', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:canned-tunas', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:ketchups', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:mustards', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:mayonnaises', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:salad-dressings', categoryId: 'canned_sauces', priority: SPECIFIC },
  { tag: 'en:condiments', categoryId: 'canned_sauces', priority: MID },
  { tag: 'en:sauces', categoryId: 'canned_sauces', priority: MID },
  { tag: 'en:canned-foods', categoryId: 'canned_sauces', priority: MID },

  // snacks
  { tag: 'en:chocolates', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:dark-chocolates', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:milk-chocolates', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:candies', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:gummies', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:cookies', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:biscuits', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:wafers', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:salty-snacks', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:chips', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:crisps', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:tortilla-chips', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:pretzels', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:crackers', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:popcorn', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:salted-nuts', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:roasted-nuts', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:dried-fruits', categoryId: 'snacks', priority: SPECIFIC },
  { tag: 'en:sweet-snacks', categoryId: 'snacks', priority: MID },
  { tag: 'en:snacks', categoryId: 'snacks', priority: GENERIC },

  // beverages
  { tag: 'en:waters', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:mineral-waters', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:spring-waters', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:carbonated-waters', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:fruit-juices', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:apple-juices', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:orange-juices', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:smoothies', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:sodas', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:colas', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:lemonades', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:iced-teas', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:energy-drinks', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:beers', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:lagers', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:ales', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:wines', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:red-wines', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:white-wines', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:sparkling-wines', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:champagnes', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:spirits', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:liquors', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:gins', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:rums', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:vodkas', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:whiskies', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:ciders', categoryId: 'beverages', priority: SPECIFIC },
  { tag: 'en:alcoholic-beverages', categoryId: 'beverages', priority: MID },
  { tag: 'en:beverages', categoryId: 'beverages', priority: GENERIC },

  // drugstore
  { tag: 'en:hygiene', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:body-care', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:shampoos', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:shower-gels', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:soaps', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:toothpastes', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:toothbrushes', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:deodorants', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:creams-and-lotions', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:sun-creams', categoryId: 'drugstore', priority: SPECIFIC },
  { tag: 'en:shaving-creams', categoryId: 'drugstore', priority: SPECIFIC },

  // baby_kids
  { tag: 'en:baby-foods', categoryId: 'baby_kids', priority: SPECIFIC },
  { tag: 'en:baby-milks', categoryId: 'baby_kids', priority: SPECIFIC },
  { tag: 'en:infant-formulas', categoryId: 'baby_kids', priority: SPECIFIC },
  { tag: 'en:baby-cereals', categoryId: 'baby_kids', priority: SPECIFIC },
  { tag: 'en:baby-purees', categoryId: 'baby_kids', priority: SPECIFIC },

  // household
  { tag: 'en:cleaning-products', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:dishwashing-detergents', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:laundry-detergents', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:fabric-softeners', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:trash-bags', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:toilet-papers', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:paper-towels', categoryId: 'household', priority: SPECIFIC },
  { tag: 'en:aluminum-foils', categoryId: 'household', priority: SPECIFIC },

  // pet_supplies
  { tag: 'en:pet-food', categoryId: 'pet_supplies', priority: SPECIFIC },
  { tag: 'en:cat-food', categoryId: 'pet_supplies', priority: SPECIFIC },
  { tag: 'en:dog-food', categoryId: 'pet_supplies', priority: SPECIFIC },
  { tag: 'en:bird-food', categoryId: 'pet_supplies', priority: SPECIFIC },
  { tag: 'en:cat-litter', categoryId: 'pet_supplies', priority: SPECIFIC },

  // meat_poultry
  { tag: 'en:poultry', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:chickens', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:turkeys', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:beef', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:porks', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:veal', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:lamb', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:minced-meat', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:steaks', categoryId: 'meat_poultry', priority: SPECIFIC },
  { tag: 'en:meats', categoryId: 'meat_poultry', priority: MID },

  // fish_seafood
  { tag: 'en:fishes', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:fresh-fishes', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:salmons', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:trouts', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:seafood', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:crustaceans', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:shrimps', categoryId: 'fish_seafood', priority: SPECIFIC },
  { tag: 'en:molluscs', categoryId: 'fish_seafood', priority: SPECIFIC },

  // deli_cold_cuts
  { tag: 'en:charcuterie', categoryId: 'deli_cold_cuts', priority: SPECIFIC },
  { tag: 'en:hams', categoryId: 'deli_cold_cuts', priority: SPECIFIC },
  { tag: 'en:sausages', categoryId: 'deli_cold_cuts', priority: SPECIFIC },
  { tag: 'en:cold-cuts', categoryId: 'deli_cold_cuts', priority: SPECIFIC },
  { tag: 'en:salamis', categoryId: 'deli_cold_cuts', priority: SPECIFIC },
  { tag: 'en:prosciutto', categoryId: 'deli_cold_cuts', priority: SPECIFIC },
  { tag: 'en:pates', categoryId: 'deli_cold_cuts', priority: SPECIFIC },

  // plant_based
  { tag: 'en:meat-substitutes', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:tofu', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:tempeh', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:seitan', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:plant-based-steaks', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:plant-based-burgers', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:plant-based-sausages', categoryId: 'plant_based', priority: SPECIFIC },
  { tag: 'en:vegan-cheeses', categoryId: 'plant_based', priority: SPECIFIC },

  // dairy_eggs
  { tag: 'en:fresh-milks', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:pasteurized-milks', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:milks', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:cheeses', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:fresh-cheeses', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:curd-cheeses', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:cottage-cheeses', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:yogurts', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:plain-yogurts', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:fruit-yogurts', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:creams', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:sour-creams', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:butters', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:margarines', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:dairy-spreads', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:eggs', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:puddings', categoryId: 'dairy_eggs', priority: SPECIFIC },
  { tag: 'en:dairies', categoryId: 'dairy_eggs', priority: MID },

  // frozen
  { tag: 'en:frozen-foods', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-fruits', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-vegetables', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-berries', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-pizzas', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-ready-meals', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-desserts', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-fishes', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-meats', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:frozen-french-fries', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:ice-creams', categoryId: 'frozen', priority: SPECIFIC },
  { tag: 'en:sorbets', categoryId: 'frozen', priority: SPECIFIC },

  // checkout
  { tag: 'en:chewing-gums', categoryId: 'checkout', priority: SPECIFIC },
];
